"""
PrawnikGPT Backend - Query Management Models

Pydantic models for query-related endpoints:
- POST /api/v1/queries (submit query)
- GET /api/v1/queries (list queries)
- GET /api/v1/queries/{query_id} (query details)
- POST /api/v1/queries/{query_id}/accurate-response (request accurate response)

These models mirror the TypeScript types in src/lib/types.ts for type consistency.
"""

from pydantic import BaseModel, Field, field_validator
from typing import Literal, Optional, List
from datetime import datetime
from uuid import UUID


# =========================================================================
# ENUMS AND TYPE ALIASES
# =========================================================================

QueryProcessingStatus = Literal["pending", "processing", "completed", "failed"]
ResponseType = Literal["fast", "accurate"]


# =========================================================================
# SHARED COMPONENTS
# =========================================================================

class SourceReference(BaseModel):
    """
    Reference to a legal act source used in response generation.
    
    Links response content back to specific legal acts and articles.
    """
    act_title: str = Field(
        ...,
        description="Title of the legal act"
    )
    article: str = Field(
        ...,
        description="Article/section reference (e.g., 'Art. 123', 'Art. 45 § 2')"
    )
    link: str = Field(
        ...,
        description="URL to full text of legal act"
    )
    chunk_id: str = Field(
        ...,
        description="Internal chunk ID for tracking"
    )
    
    model_config = {
        "json_schema_extra": {
            "example": {
                "act_title": "Ustawa z dnia 23 kwietnia 1964 r. - Kodeks cywilny",
                "article": "Art. 535",
                "link": "https://isap.sejm.gov.pl/isap.nsf/DocDetails.xsp?id=WDU19640160093",
                "chunk_id": "chunk_123e4567"
            }
        }
    }


class RatingSummary(BaseModel):
    """
    Simplified rating information (embedded in responses).
    """
    value: Literal["up", "down"] = Field(
        ...,
        description="Rating value"
    )


class RatingDetail(RatingSummary):
    """
    Detailed rating information with metadata.
    """
    rating_id: str = Field(
        ...,
        description="Unique rating identifier"
    )
    created_at: datetime = Field(
        ...,
        description="When rating was created"
    )


class PaginationMetadata(BaseModel):
    """
    Pagination metadata for list responses.
    """
    page: int = Field(
        ...,
        ge=1,
        description="Current page number (1-indexed)"
    )
    per_page: int = Field(
        ...,
        ge=1,
        le=100,
        description="Items per page"
    )
    total_pages: int = Field(
        ...,
        ge=0,
        description="Total number of pages"
    )
    total_count: int = Field(
        ...,
        ge=0,
        description="Total number of items"
    )


# =========================================================================
# REQUEST MODELS
# =========================================================================

class QuerySubmitRequest(BaseModel):
    """
    Request body for submitting a new query.
    
    POST /api/v1/queries
    """
    query_text: str = Field(
        ...,
        min_length=10,
        max_length=1000,
        description="Legal question in natural language (Polish)"
    )
    
    @field_validator('query_text')
    @classmethod
    def validate_query_text(cls, v: str) -> str:
        """Validate query text is not just whitespace"""
        if not v.strip():
            raise ValueError("Query text cannot be empty or only whitespace")
        return v.strip()
    
    model_config = {
        "json_schema_extra": {
            "example": {
                "query_text": "Jakie są warunki zawarcia umowy sprzedaży nieruchomości?"
            }
        }
    }


# =========================================================================
# RESPONSE MODELS - FAST RESPONSE
# =========================================================================

class FastResponseData(BaseModel):
    """
    Fast response data structure.
    
    Generated by smaller model (7B-13B) in <15 seconds.
    """
    content: str = Field(
        ...,
        description="Generated response text"
    )
    model_name: str = Field(
        ...,
        description="Name of LLM model used (e.g., 'mistral:7b')"
    )
    generation_time_ms: int = Field(
        ...,
        ge=0,
        description="Time taken to generate response (milliseconds)"
    )
    sources: List[SourceReference] = Field(
        ...,
        description="Legal act sources used in response"
    )
    rating: Optional[RatingDetail] = Field(
        None,
        description="User rating (if provided)"
    )


class FastResponseStatus(BaseModel):
    """
    Fast response status (for pending/processing state).
    """
    status: QueryProcessingStatus = Field(
        ...,
        description="Processing status"
    )
    estimated_time_seconds: int = Field(
        ...,
        ge=0,
        le=15,
        description="Estimated time to completion (seconds)"
    )


# =========================================================================
# RESPONSE MODELS - ACCURATE RESPONSE
# =========================================================================

class AccurateResponseData(BaseModel):
    """
    Accurate response data structure.
    
    Generated by larger model (120B) in up to 240 seconds.
    """
    content: str = Field(
        ...,
        description="Generated response text (more detailed)"
    )
    model_name: str = Field(
        ...,
        description="Name of LLM model used (e.g., 'gpt-oss:120b')"
    )
    generation_time_ms: int = Field(
        ...,
        ge=0,
        description="Time taken to generate response (milliseconds)"
    )
    sources: List[SourceReference] = Field(
        ...,
        description="Legal act sources used in response"
    )
    rating: Optional[RatingDetail] = Field(
        None,
        description="User rating (if provided)"
    )


class AccurateResponseStatus(BaseModel):
    """
    Accurate response status (for pending/processing state).
    """
    status: QueryProcessingStatus = Field(
        ...,
        description="Processing status"
    )
    estimated_time_seconds: int = Field(
        ...,
        ge=0,
        le=240,
        description="Estimated time to completion (seconds)"
    )


# =========================================================================
# RESPONSE MODELS - QUERY SUBMISSION
# =========================================================================

class QuerySubmitResponse(BaseModel):
    """
    Response for initial query submission (202 Accepted).
    
    POST /api/v1/queries
    Returned immediately when query is submitted, before processing completes.
    """
    query_id: str = Field(
        ...,
        description="Unique query identifier (UUID)"
    )
    query_text: str = Field(
        ...,
        description="Submitted query text"
    )
    status: QueryProcessingStatus = Field(
        ...,
        description="Overall query processing status"
    )
    created_at: datetime = Field(
        ...,
        description="When query was created"
    )
    fast_response: FastResponseStatus = Field(
        ...,
        description="Fast response processing status"
    )
    
    model_config = {
        "json_schema_extra": {
            "example": {
                "query_id": "123e4567-e89b-12d3-a456-426614174000",
                "query_text": "Jakie są warunki zawarcia umowy sprzedaży nieruchomości?",
                "status": "processing",
                "created_at": "2025-11-19T10:30:00Z",
                "fast_response": {
                    "status": "processing",
                    "estimated_time_seconds": 12
                }
            }
        }
    }


# =========================================================================
# RESPONSE MODELS - QUERY DETAILS
# =========================================================================

class FastResponseDetail(BaseModel):
    """
    Fast response detail in query detail response.
    """
    status: QueryProcessingStatus
    content: Optional[str] = None
    model_name: Optional[str] = None
    generation_time_ms: Optional[int] = None
    sources: Optional[List[SourceReference]] = None
    rating: Optional[RatingDetail] = None


class AccurateResponseDetail(BaseModel):
    """
    Accurate response detail in query detail response.
    """
    status: QueryProcessingStatus
    content: Optional[str] = None
    model_name: Optional[str] = None
    generation_time_ms: Optional[int] = None
    sources: Optional[List[SourceReference]] = None
    rating: Optional[RatingDetail] = None


class QueryDetailResponse(BaseModel):
    """
    Full query details with all responses.
    
    GET /api/v1/queries/{query_id}
    POST /api/v1/queries (after processing completes)
    """
    query_id: str = Field(
        ...,
        description="Unique query identifier"
    )
    query_text: str = Field(
        ...,
        description="Original query text"
    )
    status: QueryProcessingStatus = Field(
        ...,
        description="Overall query status"
    )
    created_at: datetime = Field(
        ...,
        description="When query was created"
    )
    fast_response: FastResponseDetail = Field(
        ...,
        description="Fast response details"
    )
    accurate_response: Optional[AccurateResponseDetail] = Field(
        None,
        description="Accurate response details (if requested)"
    )


# =========================================================================
# RESPONSE MODELS - QUERY LIST
# =========================================================================

class QueryListItemFastResponse(BaseModel):
    """
    Fast response summary for list view.
    """
    content: str
    model_name: str
    generation_time_ms: int
    sources_count: int = Field(
        ...,
        description="Number of sources (not full source list)"
    )
    rating: Optional[RatingSummary] = None


class QueryListItemAccurateResponse(BaseModel):
    """
    Accurate response summary for list view.
    """
    exists: bool = Field(
        ...,
        description="Whether accurate response exists"
    )
    model_name: Optional[str] = None
    generation_time_ms: Optional[int] = None
    rating: Optional[RatingSummary] = None


class QueryListItem(BaseModel):
    """
    Single query item in list view (simplified).
    """
    query_id: str
    query_text: str
    created_at: datetime
    fast_response: QueryListItemFastResponse
    accurate_response: Optional[QueryListItemAccurateResponse] = None


class QueryListResponse(BaseModel):
    """
    Paginated list of queries.
    
    GET /api/v1/queries
    """
    queries: List[QueryListItem] = Field(
        ...,
        description="List of query items for current page"
    )
    pagination: PaginationMetadata = Field(
        ...,
        description="Pagination metadata"
    )


# =========================================================================
# RESPONSE MODELS - ACCURATE RESPONSE REQUEST
# =========================================================================

class AccurateResponseSubmitResponse(BaseModel):
    """
    Response for accurate response request (202 Accepted).
    
    POST /api/v1/queries/{query_id}/accurate-response
    Initial response before processing completes.
    """
    query_id: str
    accurate_response: AccurateResponseStatus


class AccurateResponseCompletedResponse(BaseModel):
    """
    Response when accurate response processing completes.
    
    POST /api/v1/queries/{query_id}/accurate-response (after completion)
    """
    query_id: str
    accurate_response: AccurateResponseData

